# Generated by Django 4.0.2 on 2022-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='veterinarios',
        ),
    ]
