# Generated by Django 3.2.5 on 2022-04-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_name', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('dueno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
