# Generated by Django 4.0.2 on 2022-04-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20220423_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
    ]
