# Generated by Django 4.0.2 on 2022-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_usuarios_veterinarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_clinico',
            name='mascota_historial',
            field=models.CharField(default='historial vacio', max_length=2000),
        ),
    ]
