# Generated by Django 4.0.2 on 2022-05-30 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_historial_clinico_mascota_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='fecha_cita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citas',
            name='razon',
            field=models.CharField(default='sin razon aparente', max_length=400),
        ),
    ]
